version: "3"
services:
  mysql:
    restart: unless-stopped
    image: 'mariadb:10.6'
    environment:
      - 'MYSQL_USER=${DB_USER}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_DATABASE=${DB_NAME}'
      - 'MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}'
    volumes:
      - 'db:/var/lib/mysql'
  fpm:
    restart: unless-stopped
    image: 'martadinata666/akaunting:latest'
    depends_on:
      - 'mysql'
    volumes:
      - 'htdocs:/var/www/html'
      - 'storage:/var/www/html/storage'
      - 'modules:/var/www/html/modules'
  apache:
    restart: unless-stopped
    image: 'martadinata666/apache:fcgid'
    environment:
      - 'TZ=Asia/Kolkata'
    volumes_from:
      - fpm:rw
    depends_on:
      - 'fpm'
    ports:
      - '${AKAUNTING_PORT}:80'
volumes: 
  modules:
  storage:
  htdocs:
  db: