version: "3"
services:
  mysql:
    restart: unless-stopped
    image: 'sameersbn/mysql:5.7.24'
    environment:
      - 'DB_USER=${DB_USER}'
      - 'DB_PASS=${DB_PASSWORD}'
      - 'DB_NAME=${DB_NAME}'
    volumes:
      - '${MYSQL_DATA}:/var/lib/mysql'
  akaunting:
    restart: unless-stopped
    image: 'sameersbn/akaunting:1.3.9'
    command: app:akaunting
    environment:
      - 'DEBUG=false'
      - 'TZ=Asia/Kolkata'
      - 'DB_HOST=mysql'
      - 'DB_USER=${DB_USER}'
      - 'DB_PASS=${DB_PASSWORD}'
      - 'DB_NAME=${DB_NAME}'
      - 'AKAUNTING_URL=https://get-deck.com/'
      - 'AKAUNTING_COMPANY_NAME=${COMPANY_NAME}'
      - 'AKAUNTING_COMPANY_EMAIL=${COMPANY_EMAIL}'
      - 'AKAUNTING_ADMIN_EMAIL=${ADMIN_EMAIL}'
      - 'AKAUNTING_ADMIN_PASSWORD=${ADMIN_PASSWORD}'
      - 'AKAUNTING_BACKUPS_EXPIRY=0'
    depends_on:
      - 'mysql'
    volumes:
      - '${APP_CODE_PATH_HOST}:/var/lib/akaunting'
  nginx:
    restart: unless-stopped
    image: 'sameersbn/akaunting:1.3.9'
    command: app:nginx
    environment:
      - 'AKAUNTING_PHP_FPM_HOST=akaunting'
      - 'AKAUNTING_PHP_FPM_PORT=9000'
    depends_on:
      - 'akaunting'
    ports:
      - '${AKAUNTING_PORT}:80'
volumes:
  mysql:
  akaunting: